### ISSUE TITLE
Auth Cookie 

### ISSUE THREAD

**Issue by PhilipStefanov** [sonyxperiadev/pygerrit#36]
How can i use cookie based authentication to sent GET requests to Gerrit API ?
Something like curl -b, --cookie <name=data>
              (HTTP) Pass the data to the HTTP server as a cookie. It is supposedly the data previously received from the server in a "Set-Cookie:" line.  The data should  be
              in the format "NAME1=VALUE1; NAME2=VALUE2".

**Comment by dpursehouse** [comment]
pygerrit uses the requests library which has cookie support when using the `Session` object, but I removed usage of `Session` in 964bed0993f1f01bd9eb5746ef26c089ad2a4369 due to some incompatibilities with Gerrit. (See the commit message there for more detail).

It might be possible to implement a custom authentication, but I haven't looked into it yet.

Note that I am no longer maintaining this project.  I have moved development to [pygerrit2](https://github.com/dpursehouse/pygerrit2).
